version: 2

models:
  - name: dim_food_group
    columns:
      - name: food_group_id
        data_tests:
          - not_null
          - unique
      - name: food_group_name
        data_tests:
          - not_null
      - name: source
        data_tests:
          - not_null

  - name: dim_food
    columns:
      - name: food_id
        data_tests:
          - not_null
          - unique
      - name: food_name
        data_tests:
          - not_null
      - name: food_group_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_food_group')
              field: food_group_id
      - name: source
        data_tests:
          - not_null

  - name: dim_nutrient
    columns:
      - name: nutrient_id
        data_tests:
          - not_null
          - unique
      - name: nutrient_name
        data_tests:
          - not_null
          - unique
      - name: unit
        data_tests:
          - not_null
      - name: category
        data_tests:
          - not_null

  - name: fact_nutrient_values
    columns:
      - name: food_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_food')
              field: food_id
      - name: nutrient_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_nutrient')
              field: nutrient_id
